name: Deploy
on:
  workflow_dispatch:
  push:
     branches: [ main ]

defaults:
  run:
    shell: bash

env:
  LINK: https://mega.nz/file/ZF0hDAQY#EZBVXr4IEAew8aN5mkWc7W-7qtbfySRHZsPq6nBrsms
  RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
  TYPE_FILE: zip

jobs:
  process:
    runs-on: ubuntu-latest
    if: github.actor == 'c3eru'
    container:
      image: anggit86/docker:mirrorer

    steps:
      - uses: actions/checkout@v2
      - name: setup config drive
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf

      - name: Download
        run: |
          mega-get ${LINK} $PWD

      - name: Upload
        run: |
          rclone copy --drive-chunk-size 256M --stats 1s $PWD/*.${TYPE_FILE} mobx: -P

      - name: Link Download
        run: |
          LINK_MIRROR=https://nfsproject.projek.workers.dev/1:/$(basename $PWD/*.${TYPE_FILE})
          echo ${LINK_MIRROR}
