name: Deploy
on:
  workflow_dispatch:
  push:
     branches: [ main ]

defaults:
  run:
    shell: bash

env:
  SF_USERNAME: ${{ secrets.SF_USER }}
  SF_PASSWORD: ${{ secrets.SF_PASWORD }}
  LINK: https://mega.nz/file/oJV1wbJJ#mp0Fxw7V0EExcbvr-YH3Sc2zxBnhq5Q07QxX3KNpHVU
  RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
  TYPE_FILE: zip
  


jobs:
  process:
    runs-on: ubuntu-latest
    if: github.actor == 'c3eru'
    container:
      image: anggit86/docker:mirrorer

    steps:
      - uses: actions/checkout@v2
      - name: setup config drive
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf

      - name: SSH agent
        uses: fastai/workflows/ssh@master
        with:
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          key_file: frs.sourceforge.net

      - name: Download
        run: |
          mega-get ${LINK} $PWD

      - name: Upload
        run: |
          rclone copy --drive-chunk-size 256M --stats 1s $PWD/*.${TYPE_FILE} rom: -P
